version: "3.9"
services:
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=spotify_user
      - MYSQL_DATABASE=spotify_db
    ports:
      - "3306:3306"
    container_name: db
    volumes:
      - type: bind
        source: ./init.sql
        target: /mariadb-volume/init.sql
      - type: bind
        source: ./data.csv
        target: /mariadb-volume/data.csv
    command: --init-file /mariadb-volume/init.sql
    networks:
      - local

volumes:
  mariadb-volume:

networks:
  local:
    driver: bridge